WITH missing AS (
    SELECT
        id,
        row_number() OVER (ORDER BY id) AS sequence_number
    FROM locations
    WHERE compatibility_id IS NULL
)
UPDATE locations location
SET compatibility_id = 100000000000 + missing.sequence_number
FROM missing
WHERE missing.id = location.id;

ALTER TABLE locations
    ALTER COLUMN compatibility_id SET NOT NULL;

ALTER TABLE locations
    ALTER COLUMN compatibility_id
    ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 200000000000);
